{
 "title": "KRaft",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_server_raft_metrics_current_state, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "KRaft Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics_high_watermark{namespace=\"$namespace\", job=\"kafka-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Cluster ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Brokers Count",
   "type": "stat",
   "description": "When using KRaft, the number of registered and unfenced brokers as observed by this controller.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activebrokercount{namespace=\"$namespace\", job=\"kafka-controller\"})/count(kafka_controller_kafkacontroller_activebrokercount{namespace=\"$namespace\", job=\"kafka-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fenced Broker Count",
   "type": "stat",
   "description": "When using KRaft, the number of registered but fenced brokers as observed by this controller.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_fencedbrokercount{namespace=\"$namespace\", job=\"kafka-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brokers Count",
   "type": "timeseries",
   "description": "When using KRaft, the number of registered and unfenced brokers as observed by this controller.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "KRaft Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Leader",
   "type": "stat",
   "description": "The current quorum leader’s id; -1 indicates unknown.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_raft_metrics_current_leader{namespace=\"$namespace\", job=\"kafka-controller\"})/count(kafka_server_raft_metrics_current_leader{namespace=\"$namespace\", job=\"kafka-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current quorum epoch.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics_current_epoch{namespace=\"$namespace\", job=\"kafka-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Error Count",
   "type": "stat",
   "description": "The number of times this controller node has encountered an error during metadata log processing.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_metadataerrorcount{namespace=\"$namespace\", job=\"kafka-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record lag ms",
   "type": "timeseries",
   "description": "The difference between now and the timestamp of the last record from the cluster metadata partition that was applied by the controller. For active controllers the value of this lag is always zero.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_lastappliedrecordlagms{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Maximum time spent on electing a new leader",
   "type": "timeseries",
   "description": "The maximum time in milliseconds spent on electing a new leader.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_election_latency_max{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Append Records Rate",
   "type": "timeseries",
   "description": "The average number of records appended per sec by the leader of the raft quorum.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_append_records_rate{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average time spent to commit an entry in the raft log",
   "type": "timeseries",
   "description": "The average time in milliseconds to commit an entry in the raft log.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_commit_latency_avg{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fetch Record Rate",
   "type": "timeseries",
   "description": "The average number of records fetched from the leader of the raft quorum.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_fetch_records_rate{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fetch Record Rate",
   "type": "timeseries",
   "description": "The average number of records fetched from the leader of the raft quorum.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_fetch_records_rate{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent waiting in the Controller Event Queue ms",
   "type": "timeseries",
   "description": "A Histogram of the time in milliseconds that requests spent waiting in the Controller Event Queue.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_controller_controllereventmanager_eventqueuetimems{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}} - quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Time spent processed in the Controller Event Queue ms",
   "type": "timeseries",
   "description": "A Histogram of the time in milliseconds that requests spent being processed in the Controller Event Queue.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_controller_controllereventmanager_eventqueueprocessingtimems{namespace=\"$namespace\", job=\"kafka-controller\"}",
     "legendFormat": "{{pod}} - quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"kafka-controller\",namespace=\"$namespace\"}[5m])*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_used_bytes{job=\"kafka-controller\",namespace=\"$namespace\"})",
     "legendFormat": "Used:{{pod}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"kafka-controller\",namespace=\"$namespace\",area=\"heap\"}",
     "legendFormat": "Max:{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-controller\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}